### ISSUE TITLE
Scala 2.12 build

### ISSUE THREAD

**Issue by dbronecki** [NewMotion/scala-geocode#3]
Hi,
Could you provide build for Scala 2.12 ?

**Comment by reinierl** [comment]
I released a version 2.3 with all the latest dependencies for Scala 2.11 and 2.12.

**Comment by dbronecki** [comment]
@reinierl I can't use 2.3 version. SBT raises unresolved dependency error:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.thenewmotion#geocode_2.11;2.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

I guess the reason is that build failed on master (https://travis-ci.org/NewMotion/scala-geocode/builds/263098954)

**Comment by reinierl** [comment]
Hmm, the Travis build is failing because the information in the .travis.yml is outdated, that shouldn't stop SBT from finding the artifact.

Ah, I see you're using "geocode" instead of "scala-geocode" as the artifact name. That is the problem. And our README is spreading this misinformation.

I fixed both the README and travis.yml. When you change your build.sbt to refer to "scala-geocode" instead of "geocode" it should work.
